/******************************************************************************
 *
 * Copyright(c) 2016 - 2017 Realtek Corporation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 ******************************************************************************/

#ifndef _HALMAC_TX_DESC_BUFFER_AP_H_
#define _HALMAC_TX_DESC_BUFFER_AP_H_
#if (HALMAC_8814B_SUPPORT)

/*TXDESC_WORD0*/

#define SET_TX_DESC_BUFFER_RDG_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0x1, 31)
#define SET_TX_DESC_BUFFER_RDG_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0x1, 31)
#define GET_TX_DESC_BUFFER_RDG_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, 0x1, 31)
#define SET_TX_DESC_BUFFER_BCNPKT_TSF_CTRL(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0x1, 30)
#define SET_TX_DESC_BUFFER_BCNPKT_TSF_CTRL_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0x1, 30)
#define GET_TX_DESC_BUFFER_BCNPKT_TSF_CTRL(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, 0x1, 30)
#define SET_TX_DESC_BUFFER_AGG_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0x1, 29)
#define SET_TX_DESC_BUFFER_AGG_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0x1, 29)
#define GET_TX_DESC_BUFFER_AGG_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, 0x1, 29)
#define SET_TX_DESC_BUFFER_PKT_OFFSET(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0x1f, 24)
#define SET_TX_DESC_BUFFER_PKT_OFFSET_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0x1f, 24)
#define GET_TX_DESC_BUFFER_PKT_OFFSET(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, 0x1f, 24)
#define SET_TX_DESC_BUFFER_OFFSET(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0xff, 16)
#define SET_TX_DESC_BUFFER_OFFSET_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0xff, 16)
#define GET_TX_DESC_BUFFER_OFFSET(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, 0xff, 16)
#define SET_TX_DESC_BUFFER_TXPKTSIZE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0xffff, 0)
#define SET_TX_DESC_BUFFER_TXPKTSIZE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, __Value, 0xffff, 0)
#define GET_TX_DESC_BUFFER_TXPKTSIZE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword0, 0xffff, 0)

/*TXDESC_WORD1*/

#define SET_TX_DESC_BUFFER_USERATE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 31)
#define SET_TX_DESC_BUFFER_USERATE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 31)
#define GET_TX_DESC_BUFFER_USERATE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0x1, 31)
#define SET_TX_DESC_BUFFER_AMSDU(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 30)
#define SET_TX_DESC_BUFFER_AMSDU_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 30)
#define GET_TX_DESC_BUFFER_AMSDU(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0x1, 30)
#define SET_TX_DESC_BUFFER_EN_HWSEQ(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 29)
#define SET_TX_DESC_BUFFER_EN_HWSEQ_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 29)
#define GET_TX_DESC_BUFFER_EN_HWSEQ(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0x1, 29)
#define SET_TX_DESC_BUFFER_EN_HWEXSEQ(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 28)
#define SET_TX_DESC_BUFFER_EN_HWEXSEQ_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 28)
#define GET_TX_DESC_BUFFER_EN_HWEXSEQ(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0x1, 28)
#define SET_TX_DESC_BUFFER_SW_SEQ(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0xfff, 16)
#define SET_TX_DESC_BUFFER_SW_SEQ_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0xfff, 16)
#define GET_TX_DESC_BUFFER_SW_SEQ(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0xfff, 16)
#define SET_TX_DESC_BUFFER_DROP_ID(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x3, 14)
#define SET_TX_DESC_BUFFER_DROP_ID_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x3, 14)
#define GET_TX_DESC_BUFFER_DROP_ID(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0x3, 14)
#define SET_TX_DESC_BUFFER_MOREDATA(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 13)
#define SET_TX_DESC_BUFFER_MOREDATA_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1, 13)
#define GET_TX_DESC_BUFFER_MOREDATA(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0x1, 13)
#define SET_TX_DESC_BUFFER_QSEL(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1f, 8)
#define SET_TX_DESC_BUFFER_QSEL_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0x1f, 8)
#define GET_TX_DESC_BUFFER_QSEL(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0x1f, 8)
#define SET_TX_DESC_BUFFER_MACID(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0xff, 0)
#define SET_TX_DESC_BUFFER_MACID_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, __Value, 0xff, 0)
#define GET_TX_DESC_BUFFER_MACID(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword1, 0xff, 0)

/*TXDESC_WORD2*/

#define SET_TX_DESC_BUFFER_CHK_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x1, 31)
#define SET_TX_DESC_BUFFER_CHK_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x1, 31)
#define GET_TX_DESC_BUFFER_CHK_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, 0x1, 31)
#define SET_TX_DESC_BUFFER_DISQSELSEQ(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x1, 30)
#define SET_TX_DESC_BUFFER_DISQSELSEQ_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x1, 30)
#define GET_TX_DESC_BUFFER_DISQSELSEQ(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, 0x1, 30)
#define SET_TX_DESC_BUFFER_SND_PKT_SEL(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x3, 28)
#define SET_TX_DESC_BUFFER_SND_PKT_SEL_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x3, 28)
#define GET_TX_DESC_BUFFER_SND_PKT_SEL(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, 0x3, 28)
#define SET_TX_DESC_BUFFER_DMA_PRI(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x1, 26)
#define SET_TX_DESC_BUFFER_DMA_PRI_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x1, 26)
#define GET_TX_DESC_BUFFER_DMA_PRI(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, 0x1, 26)
#define SET_TX_DESC_BUFFER_MAX_AMSDU_MODE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x3, 24)
#define SET_TX_DESC_BUFFER_MAX_AMSDU_MODE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0x3, 24)
#define GET_TX_DESC_BUFFER_MAX_AMSDU_MODE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, 0x3, 24)
#define SET_TX_DESC_BUFFER_DMA_TXAGG_NUM(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0xff, 16)
#define SET_TX_DESC_BUFFER_DMA_TXAGG_NUM_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0xff, 16)
#define GET_TX_DESC_BUFFER_DMA_TXAGG_NUM(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, 0xff, 16)
#define SET_TX_DESC_BUFFER_TXDESC_CHECKSUM(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0xffff, 0)
#define SET_TX_DESC_BUFFER_TXDESC_CHECKSUM_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, __Value, 0xffff, 0)
#define GET_TX_DESC_BUFFER_TXDESC_CHECKSUM(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword2, 0xffff, 0)

/*TXDESC_WORD3*/

#define SET_TX_DESC_BUFFER_OFFLOAD_SIZE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0x7fff, 16)
#define SET_TX_DESC_BUFFER_OFFLOAD_SIZE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0x7fff, 16)
#define GET_TX_DESC_BUFFER_OFFLOAD_SIZE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, 0x7fff, 16)
#define SET_TX_DESC_BUFFER_CHANNEL_DMA(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0x1f, 11)
#define SET_TX_DESC_BUFFER_CHANNEL_DMA_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0x1f, 11)
#define GET_TX_DESC_BUFFER_CHANNEL_DMA(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, 0x1f, 11)
#define SET_TX_DESC_BUFFER_MBSSID(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0xf, 7)
#define SET_TX_DESC_BUFFER_MBSSID_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0xf, 7)
#define GET_TX_DESC_BUFFER_MBSSID(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, 0xf, 7)
#define SET_TX_DESC_BUFFER_BK(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0x1, 6)
#define SET_TX_DESC_BUFFER_BK_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0x1, 6)
#define GET_TX_DESC_BUFFER_BK(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, 0x1, 6)
#define SET_TX_DESC_BUFFER_WHEADER_LEN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0x1f, 0)
#define SET_TX_DESC_BUFFER_WHEADER_LEN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, __Value, 0x1f, 0)
#define GET_TX_DESC_BUFFER_WHEADER_LEN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword3, 0x1f, 0)

/*TXDESC_WORD4*/

#define SET_TX_DESC_BUFFER_TRY_RATE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x1, 26)
#define SET_TX_DESC_BUFFER_TRY_RATE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x1, 26)
#define GET_TX_DESC_BUFFER_TRY_RATE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, 0x1, 26)
#define SET_TX_DESC_BUFFER_DATA_BW(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x3, 24)
#define SET_TX_DESC_BUFFER_DATA_BW_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x3, 24)
#define GET_TX_DESC_BUFFER_DATA_BW(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, 0x3, 24)
#define SET_TX_DESC_BUFFER_DATA_SHORT(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x1, 23)
#define SET_TX_DESC_BUFFER_DATA_SHORT_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x1, 23)
#define GET_TX_DESC_BUFFER_DATA_SHORT(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, 0x1, 23)
#define SET_TX_DESC_BUFFER_DATARATE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x7f, 16)
#define SET_TX_DESC_BUFFER_DATARATE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x7f, 16)
#define GET_TX_DESC_BUFFER_DATARATE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, 0x7f, 16)
#define SET_TX_DESC_BUFFER_TXBF_PATH(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x1, 11)
#define SET_TX_DESC_BUFFER_TXBF_PATH_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x1, 11)
#define GET_TX_DESC_BUFFER_TXBF_PATH(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, 0x1, 11)
#define SET_TX_DESC_BUFFER_GROUP_BIT_IE_OFFSET(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x7ff, 0)
#define SET_TX_DESC_BUFFER_GROUP_BIT_IE_OFFSET_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, __Value, 0x7ff, 0)
#define GET_TX_DESC_BUFFER_GROUP_BIT_IE_OFFSET(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword4, 0x7ff, 0)

/*TXDESC_WORD5*/

#define SET_TX_DESC_BUFFER_RTY_LMT_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 31)
#define SET_TX_DESC_BUFFER_RTY_LMT_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 31)
#define GET_TX_DESC_BUFFER_RTY_LMT_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 31)
#define SET_TX_DESC_BUFFER_HW_RTS_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 30)
#define SET_TX_DESC_BUFFER_HW_RTS_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 30)
#define GET_TX_DESC_BUFFER_HW_RTS_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 30)
#define SET_TX_DESC_BUFFER_RTS_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 29)
#define SET_TX_DESC_BUFFER_RTS_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 29)
#define GET_TX_DESC_BUFFER_RTS_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 29)
#define SET_TX_DESC_BUFFER_CTS2SELF(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 28)
#define SET_TX_DESC_BUFFER_CTS2SELF_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 28)
#define GET_TX_DESC_BUFFER_CTS2SELF(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 28)
#define SET_TX_DESC_BUFFER_TAILPAGE_H(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0xf, 24)
#define SET_TX_DESC_BUFFER_TAILPAGE_H_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0xf, 24)
#define GET_TX_DESC_BUFFER_TAILPAGE_H(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0xf, 24)
#define SET_TX_DESC_BUFFER_TAILPAGE_L(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0xff, 16)
#define SET_TX_DESC_BUFFER_TAILPAGE_L_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0xff, 16)
#define GET_TX_DESC_BUFFER_TAILPAGE_L(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0xff, 16)
#define SET_TX_DESC_BUFFER_NAVUSEHDR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 15)
#define SET_TX_DESC_BUFFER_NAVUSEHDR_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 15)
#define GET_TX_DESC_BUFFER_NAVUSEHDR(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 15)
#define SET_TX_DESC_BUFFER_BMC(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 14)
#define SET_TX_DESC_BUFFER_BMC_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 14)
#define GET_TX_DESC_BUFFER_BMC(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 14)
#define SET_TX_DESC_BUFFER_RTS_DATA_RTY_LMT(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x3f, 8)
#define SET_TX_DESC_BUFFER_RTS_DATA_RTY_LMT_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x3f, 8)
#define GET_TX_DESC_BUFFER_RTS_DATA_RTY_LMT(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x3f, 8)
#define SET_TX_DESC_BUFFER_HW_AES_IV(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 7)
#define SET_TX_DESC_BUFFER_HW_AES_IV_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 7)
#define GET_TX_DESC_BUFFER_HW_AES_IV(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 7)
#define SET_TX_DESC_BUFFER_BT_NULL(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 3)
#define SET_TX_DESC_BUFFER_BT_NULL_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 3)
#define GET_TX_DESC_BUFFER_BT_NULL(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 3)
#define SET_TX_DESC_BUFFER_EN_DESC_ID(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 2)
#define SET_TX_DESC_BUFFER_EN_DESC_ID_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x1, 2)
#define GET_TX_DESC_BUFFER_EN_DESC_ID(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x1, 2)
#define SET_TX_DESC_BUFFER_SECTYPE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x3, 0)
#define SET_TX_DESC_BUFFER_SECTYPE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, __Value, 0x3, 0)
#define GET_TX_DESC_BUFFER_SECTYPE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword5, 0x3, 0)

/*TXDESC_WORD6*/

#define SET_TX_DESC_BUFFER_MULTIPLE_PORT(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x7, 29)
#define SET_TX_DESC_BUFFER_MULTIPLE_PORT_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x7, 29)
#define GET_TX_DESC_BUFFER_MULTIPLE_PORT(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x7, 29)
#define SET_TX_DESC_BUFFER_POLLUTED(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 28)
#define SET_TX_DESC_BUFFER_POLLUTED_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 28)
#define GET_TX_DESC_BUFFER_POLLUTED(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x1, 28)
#define SET_TX_DESC_BUFFER_NULL_1(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 27)
#define SET_TX_DESC_BUFFER_NULL_1_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 27)
#define GET_TX_DESC_BUFFER_NULL_1(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x1, 27)
#define SET_TX_DESC_BUFFER_NULL_0(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 26)
#define SET_TX_DESC_BUFFER_NULL_0_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 26)
#define GET_TX_DESC_BUFFER_NULL_0(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x1, 26)
#define SET_TX_DESC_BUFFER_TRI_FRAME(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 25)
#define SET_TX_DESC_BUFFER_TRI_FRAME_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 25)
#define GET_TX_DESC_BUFFER_TRI_FRAME(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x1, 25)
#define SET_TX_DESC_BUFFER_SPE_RPT(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 24)
#define SET_TX_DESC_BUFFER_SPE_RPT_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 24)
#define GET_TX_DESC_BUFFER_SPE_RPT(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x1, 24)
#define SET_TX_DESC_BUFFER_FTM_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 23)
#define SET_TX_DESC_BUFFER_FTM_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1, 23)
#define GET_TX_DESC_BUFFER_FTM_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x1, 23)
#define SET_TX_DESC_BUFFER_MU_DATARATE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x7f, 16)
#define SET_TX_DESC_BUFFER_MU_DATARATE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x7f, 16)
#define GET_TX_DESC_BUFFER_MU_DATARATE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x7f, 16)
#define SET_TX_DESC_BUFFER_CCA_RTS(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x3, 14)
#define SET_TX_DESC_BUFFER_CCA_RTS_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x3, 14)
#define GET_TX_DESC_BUFFER_CCA_RTS(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x3, 14)
#define SET_TX_DESC_BUFFER_NDPA(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x3, 12)
#define SET_TX_DESC_BUFFER_NDPA_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x3, 12)
#define GET_TX_DESC_BUFFER_NDPA(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x3, 12)
#define SET_TX_DESC_BUFFER_TXPWR_OFSET_TYPE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x3, 9)
#define SET_TX_DESC_BUFFER_TXPWR_OFSET_TYPE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x3, 9)
#define GET_TX_DESC_BUFFER_TXPWR_OFSET_TYPE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x3, 9)
#define SET_TX_DESC_BUFFER_P_AID(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1ff, 0)
#define SET_TX_DESC_BUFFER_P_AID_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, __Value, 0x1ff, 0)
#define GET_TX_DESC_BUFFER_P_AID(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword6, 0x1ff, 0)

/*TXDESC_WORD7*/

#define SET_TX_DESC_BUFFER_SW_DEFINE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, __Value, 0xfff, 16)
#define SET_TX_DESC_BUFFER_SW_DEFINE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, __Value, 0xfff, 16)
#define GET_TX_DESC_BUFFER_SW_DEFINE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, 0xfff, 16)
#define SET_TX_DESC_BUFFER_CTRL_CNT_VALID(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, __Value, 0x1, 9)
#define SET_TX_DESC_BUFFER_CTRL_CNT_VALID_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, __Value, 0x1, 9)
#define GET_TX_DESC_BUFFER_CTRL_CNT_VALID(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, 0x1, 9)
#define SET_TX_DESC_BUFFER_CTRL_CNT(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, __Value, 0xf, 5)
#define SET_TX_DESC_BUFFER_CTRL_CNT_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, __Value, 0xf, 5)
#define GET_TX_DESC_BUFFER_CTRL_CNT(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, 0xf, 5)
#define SET_TX_DESC_BUFFER_DATA_RTY_LOWEST_RATE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, __Value, 0x1f, 0)
#define SET_TX_DESC_BUFFER_DATA_RTY_LOWEST_RATE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, __Value, 0x1f, 0)
#define GET_TX_DESC_BUFFER_DATA_RTY_LOWEST_RATE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword7, 0x1f, 0)

/*TXDESC_WORD8*/

#define SET_TX_DESC_BUFFER_PATH_MAPA(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x3, 30)
#define SET_TX_DESC_BUFFER_PATH_MAPA_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x3, 30)
#define GET_TX_DESC_BUFFER_PATH_MAPA(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0x3, 30)
#define SET_TX_DESC_BUFFER_PATH_MAPB(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x3, 28)
#define SET_TX_DESC_BUFFER_PATH_MAPB_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x3, 28)
#define GET_TX_DESC_BUFFER_PATH_MAPB(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0x3, 28)
#define SET_TX_DESC_BUFFER_PATH_MAPC(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x3, 26)
#define SET_TX_DESC_BUFFER_PATH_MAPC_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x3, 26)
#define GET_TX_DESC_BUFFER_PATH_MAPC(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0x3, 26)
#define SET_TX_DESC_BUFFER_PATH_MAPD(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x3, 24)
#define SET_TX_DESC_BUFFER_PATH_MAPD_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x3, 24)
#define GET_TX_DESC_BUFFER_PATH_MAPD(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0x3, 24)
#define SET_TX_DESC_BUFFER_ANTSEL_A(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 20)
#define SET_TX_DESC_BUFFER_ANTSEL_A_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 20)
#define GET_TX_DESC_BUFFER_ANTSEL_A(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0xf, 20)
#define SET_TX_DESC_BUFFER_ANTSEL_B(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 16)
#define SET_TX_DESC_BUFFER_ANTSEL_B_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 16)
#define GET_TX_DESC_BUFFER_ANTSEL_B(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0xf, 16)
#define SET_TX_DESC_BUFFER_ANTSEL_C(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 12)
#define SET_TX_DESC_BUFFER_ANTSEL_C_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 12)
#define GET_TX_DESC_BUFFER_ANTSEL_C(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0xf, 12)
#define SET_TX_DESC_BUFFER_ANTSEL_D(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 8)
#define SET_TX_DESC_BUFFER_ANTSEL_D_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 8)
#define GET_TX_DESC_BUFFER_ANTSEL_D(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0xf, 8)
#define SET_TX_DESC_BUFFER_NTX_PATH_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 4)
#define SET_TX_DESC_BUFFER_NTX_PATH_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0xf, 4)
#define GET_TX_DESC_BUFFER_NTX_PATH_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0xf, 4)
#define SET_TX_DESC_BUFFER_ANTLSEL_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x1, 3)
#define SET_TX_DESC_BUFFER_ANTLSEL_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x1, 3)
#define GET_TX_DESC_BUFFER_ANTLSEL_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0x1, 3)
#define SET_TX_DESC_BUFFER_AMPDU_DENSITY(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x7, 0)
#define SET_TX_DESC_BUFFER_AMPDU_DENSITY_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, __Value, 0x7, 0)
#define GET_TX_DESC_BUFFER_AMPDU_DENSITY(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword8, 0x7, 0)

/*TXDESC_WORD9*/

#define SET_TX_DESC_BUFFER_VCS_STBC(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x3, 30)
#define SET_TX_DESC_BUFFER_VCS_STBC_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x3, 30)
#define GET_TX_DESC_BUFFER_VCS_STBC(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x3, 30)
#define SET_TX_DESC_BUFFER_DATA_STBC(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x3, 28)
#define SET_TX_DESC_BUFFER_DATA_STBC_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x3, 28)
#define GET_TX_DESC_BUFFER_DATA_STBC(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x3, 28)
#define SET_TX_DESC_BUFFER_RTS_RTY_LOWEST_RATE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0xf, 24)
#define SET_TX_DESC_BUFFER_RTS_RTY_LOWEST_RATE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0xf, 24)
#define GET_TX_DESC_BUFFER_RTS_RTY_LOWEST_RATE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0xf, 24)
#define SET_TX_DESC_BUFFER_SIGNALING_TA_PKT_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 23)
#define SET_TX_DESC_BUFFER_SIGNALING_TA_PKT_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 23)
#define GET_TX_DESC_BUFFER_SIGNALING_TA_PKT_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 23)
#define SET_TX_DESC_BUFFER_MHR_CP(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 22)
#define SET_TX_DESC_BUFFER_MHR_CP_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 22)
#define GET_TX_DESC_BUFFER_MHR_CP(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 22)
#define SET_TX_DESC_BUFFER_SMH_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 21)
#define SET_TX_DESC_BUFFER_SMH_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 21)
#define GET_TX_DESC_BUFFER_SMH_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 21)
#define SET_TX_DESC_BUFFER_RTSRATE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1f, 16)
#define SET_TX_DESC_BUFFER_RTSRATE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1f, 16)
#define GET_TX_DESC_BUFFER_RTSRATE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1f, 16)
#define SET_TX_DESC_BUFFER_SMH_CAM(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0xff, 8)
#define SET_TX_DESC_BUFFER_SMH_CAM_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0xff, 8)
#define GET_TX_DESC_BUFFER_SMH_CAM(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0xff, 8)
#define SET_TX_DESC_BUFFER_ARFR_TABLE_SEL(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 7)
#define SET_TX_DESC_BUFFER_ARFR_TABLE_SEL_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 7)
#define GET_TX_DESC_BUFFER_ARFR_TABLE_SEL(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 7)
#define SET_TX_DESC_BUFFER_ARFR_HT_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 6)
#define SET_TX_DESC_BUFFER_ARFR_HT_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 6)
#define GET_TX_DESC_BUFFER_ARFR_HT_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 6)
#define SET_TX_DESC_BUFFER_ARFR_OFDM_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 5)
#define SET_TX_DESC_BUFFER_ARFR_OFDM_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 5)
#define GET_TX_DESC_BUFFER_ARFR_OFDM_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 5)
#define SET_TX_DESC_BUFFER_ARFR_CCK_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 4)
#define SET_TX_DESC_BUFFER_ARFR_CCK_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 4)
#define GET_TX_DESC_BUFFER_ARFR_CCK_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 4)
#define SET_TX_DESC_BUFFER_RTS_SHORT(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 3)
#define SET_TX_DESC_BUFFER_RTS_SHORT_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 3)
#define GET_TX_DESC_BUFFER_RTS_SHORT(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 3)
#define SET_TX_DESC_BUFFER_DISDATAFB(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 2)
#define SET_TX_DESC_BUFFER_DISDATAFB_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 2)
#define GET_TX_DESC_BUFFER_DISDATAFB(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 2)
#define SET_TX_DESC_BUFFER_DISRTSFB(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 1)
#define SET_TX_DESC_BUFFER_DISRTSFB_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 1)
#define GET_TX_DESC_BUFFER_DISRTSFB(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 1)
#define SET_TX_DESC_BUFFER_EXT_EDCA(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 0)
#define SET_TX_DESC_BUFFER_EXT_EDCA_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, __Value, 0x1, 0)
#define GET_TX_DESC_BUFFER_EXT_EDCA(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword9, 0x1, 0)

/*TXDESC_WORD10*/

#define SET_TX_DESC_BUFFER_AMPDU_MAX_TIME(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0xff, 24)
#define SET_TX_DESC_BUFFER_AMPDU_MAX_TIME_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0xff, 24)
#define GET_TX_DESC_BUFFER_AMPDU_MAX_TIME(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0xff, 24)
#define SET_TX_DESC_BUFFER_SPECIAL_CW(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 23)
#define SET_TX_DESC_BUFFER_SPECIAL_CW_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 23)
#define GET_TX_DESC_BUFFER_SPECIAL_CW(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 23)
#define SET_TX_DESC_BUFFER_RDG_NAV_EXT(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 22)
#define SET_TX_DESC_BUFFER_RDG_NAV_EXT_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 22)
#define GET_TX_DESC_BUFFER_RDG_NAV_EXT(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 22)
#define SET_TX_DESC_BUFFER_RAW(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 21)
#define SET_TX_DESC_BUFFER_RAW_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 21)
#define GET_TX_DESC_BUFFER_RAW(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 21)
#define SET_TX_DESC_BUFFER_MAX_AGG_NUM(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1f, 16)
#define SET_TX_DESC_BUFFER_MAX_AGG_NUM_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1f, 16)
#define GET_TX_DESC_BUFFER_MAX_AGG_NUM(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1f, 16)
#define SET_TX_DESC_BUFFER_FINAL_DATA_RATE(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0xff, 8)
#define SET_TX_DESC_BUFFER_FINAL_DATA_RATE_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0xff, 8)
#define GET_TX_DESC_BUFFER_FINAL_DATA_RATE(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0xff, 8)
#define SET_TX_DESC_BUFFER_GF(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 7)
#define SET_TX_DESC_BUFFER_GF_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 7)
#define GET_TX_DESC_BUFFER_GF(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 7)
#define SET_TX_DESC_BUFFER_MOREFRAG(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 6)
#define SET_TX_DESC_BUFFER_MOREFRAG_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 6)
#define GET_TX_DESC_BUFFER_MOREFRAG(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 6)
#define SET_TX_DESC_BUFFER_NOACM(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 5)
#define SET_TX_DESC_BUFFER_NOACM_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 5)
#define GET_TX_DESC_BUFFER_NOACM(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 5)
#define SET_TX_DESC_BUFFER_HTC(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 4)
#define SET_TX_DESC_BUFFER_HTC_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 4)
#define GET_TX_DESC_BUFFER_HTC(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 4)
#define SET_TX_DESC_BUFFER_TX_PKT_AFTER_PIFS(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 3)
#define SET_TX_DESC_BUFFER_TX_PKT_AFTER_PIFS_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 3)
#define GET_TX_DESC_BUFFER_TX_PKT_AFTER_PIFS(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 3)
#define SET_TX_DESC_BUFFER_USE_MAX_TIME_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 2)
#define SET_TX_DESC_BUFFER_USE_MAX_TIME_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x1, 2)
#define GET_TX_DESC_BUFFER_USE_MAX_TIME_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x1, 2)
#define SET_TX_DESC_BUFFER_HW_SSN_SEL(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x3, 0)
#define SET_TX_DESC_BUFFER_HW_SSN_SEL_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, __Value, 0x3, 0)
#define GET_TX_DESC_BUFFER_HW_SSN_SEL(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword10, 0x3, 0)

/*TXDESC_WORD11*/

#define SET_TX_DESC_BUFFER_ADDR_CAM(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0xff, 24)
#define SET_TX_DESC_BUFFER_ADDR_CAM_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0xff, 24)
#define GET_TX_DESC_BUFFER_ADDR_CAM(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, 0xff, 24)
#define SET_TX_DESC_BUFFER_SND_TARGET(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0xff, 16)
#define SET_TX_DESC_BUFFER_SND_TARGET_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0xff, 16)
#define GET_TX_DESC_BUFFER_SND_TARGET(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, 0xff, 16)
#define SET_TX_DESC_BUFFER_DATA_LDPC(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0x1, 15)
#define SET_TX_DESC_BUFFER_DATA_LDPC_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0x1, 15)
#define GET_TX_DESC_BUFFER_DATA_LDPC(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, 0x1, 15)
#define SET_TX_DESC_BUFFER_LSIG_TXOP_EN(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0x1, 14)
#define SET_TX_DESC_BUFFER_LSIG_TXOP_EN_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0x1, 14)
#define GET_TX_DESC_BUFFER_LSIG_TXOP_EN(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, 0x1, 14)
#define SET_TX_DESC_BUFFER_G_ID(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0x3f, 8)
#define SET_TX_DESC_BUFFER_G_ID_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0x3f, 8)
#define GET_TX_DESC_BUFFER_G_ID(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, 0x3f, 8)
#define SET_TX_DESC_BUFFER_SIGNALING_TA_PKT_SC(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0xf, 4)
#define SET_TX_DESC_BUFFER_SIGNALING_TA_PKT_SC_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0xf, 4)
#define GET_TX_DESC_BUFFER_SIGNALING_TA_PKT_SC(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, 0xf, 4)
#define SET_TX_DESC_BUFFER_DATA_SC(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0xf, 0)
#define SET_TX_DESC_BUFFER_DATA_SC_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, __Value, 0xf, 0)
#define GET_TX_DESC_BUFFER_DATA_SC(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword11, 0xf, 0)

/*TXDESC_WORD12*/

#define SET_TX_DESC_BUFFER_LEN1_L(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, __Value, 0x7f, 17)
#define SET_TX_DESC_BUFFER_LEN1_L_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, __Value, 0x7f, 17)
#define GET_TX_DESC_BUFFER_LEN1_L(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, 0x7f, 17)
#define SET_TX_DESC_BUFFER_LEN0(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, __Value, 0x1fff, 4)
#define SET_TX_DESC_BUFFER_LEN0_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, __Value, 0x1fff, 4)
#define GET_TX_DESC_BUFFER_LEN0(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, 0x1fff, 4)
#define SET_TX_DESC_BUFFER_PKT_NUM(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, __Value, 0xf, 0)
#define SET_TX_DESC_BUFFER_PKT_NUM_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, __Value, 0xf, 0)
#define GET_TX_DESC_BUFFER_PKT_NUM(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword12, 0xf, 0)

/*TXDESC_WORD13*/

#define SET_TX_DESC_BUFFER_LEN3(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, __Value, 0x1fff, 19)
#define SET_TX_DESC_BUFFER_LEN3_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, __Value, 0x1fff, 19)
#define GET_TX_DESC_BUFFER_LEN3(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, 0x1fff, 19)
#define SET_TX_DESC_BUFFER_LEN2(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, __Value, 0x1fff, 6)
#define SET_TX_DESC_BUFFER_LEN2_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, __Value, 0x1fff, 6)
#define GET_TX_DESC_BUFFER_LEN2(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, 0x1fff, 6)
#define SET_TX_DESC_BUFFER_LEN1_H(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, __Value, 0x3f, 0)
#define SET_TX_DESC_BUFFER_LEN1_H_NO_CLR(__pTxDesc, __Value)    HALMAC_SET_DESC_FIELD_NO_CLR(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, __Value, 0x3f, 0)
#define GET_TX_DESC_BUFFER_LEN1_H(__pTxDesc)    HALMAC_GET_DESC_FIELD(((PHALMAC_TX_DESC)__pTxDesc)->Dword13, 0x3f, 0)

#endif


#endif

